### PR TITLE
First attempt at making this code readable.

### LINKED ISSUE #14: http isn't getting replaced with https

### PR DESCRIPTION
**Pull request by hkatzdev**
Did not attempt running it because I don't run applescript on my computer

### CODE REVIEW

**Review by lukec11 — APPROVED** [review]
LGTM!!1!!

**Review by lukec11 — APPROVED** [review]
LGTM!!!2!!

**Review by hkatzdev — COMMENTED** [review]
I agree with my code

**Comment by hkatzdev** [comment]
Fixes #14

**Review by lukec11 — APPROVED** [review]

**Review by lukec11 — APPROVED** [review]

**Review by lukec11 — APPROVED** [review]

**Review by lukec11 — APPROVED** [review]

**Review by saharshxyz — APPROVED** [review]
Works when tested

**Pull request merged**
